name: wuziqi
version: '0.1'
summary: Wuziqi Game. It shows how to snap a html5 app into a snap
description: |
  This is a Wuziqi Game.

grade: stable
confinement: devmode

parts:
  webapp-container:
    source: .
    plugin: dump
    after: [webapp-helper, desktop-ubuntu-app-platform]

